experiment:
  name: "hcp_subcortical_segmentation"
  model: "unigradicon"
  weights_path: "unigradicon"

training:
  batch_size: 1
  gpus: [0, 1, 2, 3]
  epochs: 600
  eval_period: 15
  save_period: 30
  learning_rate: 0.00005
  input_shape: [175, 175, 175]
  samples_per_epoch: 4000
  similarity: "lncc"
  lambda: 1.5
  dice_loss_weight: 0.3
  lncc_sigma: 5

datasets:
  - name: "hcp_subcortical"
    weight: 1.0
    type: "unpaired_with_seg"
    image_glob: "/playpen-raid2/Data/HCP/HCP_1200/*/T1w/T1w_acpc_dc_restore_brain.nii.gz"
    segmentation_glob: "/playpen-raid2/Data/HCP/manual_subcortical_segmentations_BWH/*/*_*_novdc-label.nii.gz"
    seg_match_regex: "([0-9]+)/T1w/T1w_acpc_dc_restore_brain"
    use_cache: false
    read_type: "itk"
    is_ct: false
    quantile_range: [0.01, 0.99]
    cache_filename: "results/hcp_subcortical_cache"
    maximum_images: null
    shuffle: true
