experiment:
  name: "test_my_datasets"
  model: "unigradicon"
  weights_path: "../network_weights/unigradicon1.0/Step_2_final.trch"

training:
  batch_size: 2
  gpus: [2, 3]
  epochs: 2
  eval_period: 1
  save_period: 2
  learning_rate: 0.00005
  input_shape: [128, 128, 128]
  samples_per_epoch: 100
  similarity: "lncc"
  lambda: 1.5
  dice_loss_weight: 0.0
  lncc_sigma: 5

datasets:
  # Paired dataset example - BraTS Registration
  - name: "bratsreg"
    weight: 0.4
    type: "paired"
    image_glob: "/playpen-raid2/Data/BraTS-Reg/BraTSReg_Training_Data_v3/*/*.nii.gz"
    match_regex: "v3/(BraTSReg_[0-9]+)/"
    read_type: "itk"
    is_ct: false
    quantile_range: [0.01, 0.99]
    cache_filename: "results/test_bratsreg"
    maximum_images: 10
    shuffle: true
  - name: "pancreas"
    weight: 0.3
    type: "paired"
    image_glob: "/playpen-raid1/tgreer/pancreatic_cancer_registration/data/*/Processed/*/original_image.nii.gz"
    match_regex: "data/([0-9]+)/Processed/"
    read_type: "itk"
    is_ct: false
    quantile_range: [0.01, 0.99]
    cache_filename: "results/test_pancreas"
    maximum_images: 8
    shuffle: true
  - name: "oasis"
    weight: 0.3
    type: "unpaired"
    image_glob: "/playpen-raid2/Data/oasis/OASIS_OAS1_*_MR1/orig.nii.gz"
    read_type: "itk"
    is_ct: false
    quantile_range: [0.01, 0.99]
    cache_filename: "results/test_oasis"
    maximum_images: 12
    shuffle: true