experiment:
  name: "l2r_lungct"
  model_weights: "unigradicon"

training:
  batch_size: 2
  gpus: [0]
  epochs: 100
  eval_period: 10
  save_period: 50
  learning_rate: 0.00005
  input_shape: [175, 175, 175]
  similarity: "lncc"
  lambda: 1.5
  lncc_sigma: 5
  loss_function_masking: true

datasets:
  - name: "lungct"
    type: "paired"
    json_file: "l2r_lungct.json"
    weight: 1.0
    is_ct: true
    ct_window: [-1000, 1000]
